Repository iterative/cml.dev, pull requests merged in 2021-09, with the labels that each got.

#96 docs: docker tags
  content/docs/self-hosted-runners.md
  content/docs/usage.md
Labels: documentation

#100 yarn upgrade
  yarn.lock
Labels: 🏠 housekeeping, website

#99 sync usage from README
  content/docs/index.md
  content/docs/usage.md
Labels: documentation

#101 Clear all `yarn lint-ts` warnings
  .eslintrc.json
  src/components/organisms/SiteHeader/index.tsx
Labels: 🏠 housekeeping, website

#93 Use -1 instead of 0 to disable the idle timeout mechanism
  content/docs/self-hosted-runners.md
Labels: documentation, enhancement

#105 overhaul runners, add GCP & K8s stubs
  content/docs/cml-with-dvc.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/start/index.md
  content/docs/usage.md
  content/index.mdx
  src/components/pages/Home/HeroSection/index.tsx
Labels: documentation, p1-important

#111 add missing env var, fix typos, mic linting
  content/docs/cml-with-dvc.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/index.mdx
Labels: documentation

#112 ref: first stubs
  content/docs/ref/pr.md
  content/docs/ref/publish.md
  content/docs/ref/runner.md
  content/docs/ref/send-comment.md
  content/docs/ref/send-github-check.md
  content/docs/ref/tensorboard-dev.md
  content/docs/sidebar.json
Labels: documentation

#113 Add markdown tabs
  src/components/pages/Documentation/Markdown/ToggleProvider/index.tsx
  src/components/pages/Documentation/Markdown/index.tsx
  src/components/pages/Documentation/Markdown/styles.module.css
Labels: enhancement, p1-important, design, website
