Repository iterative/cml.dev, pull requests merged in 2021-08, with the labels that each got.

#73 rename cml-website => cml.dev, add contrib docs
  README.md
  content/docs/contributing/core.md
  content/docs/contributing/docs.md
  content/docs/sidebar.json
  package.json
  src/components/pages/Documentation/index.tsx
Labels: documentation, enhancement, 🏠 housekeeping, website

#76 update contrib guide
  content/docs/contributing/core.md
Labels: documentation

#80 Fix typo: /varibles/variables/
  content/docs/start/gitlab.md
Labels: documentation

#82 Expose access token on workflow examples
  content/docs/start/github.md
Labels: documentation

#83 sync with dvc.org
  .github/CONTRIBUTING.md
  .github/workflows/link-check-all.yml
  .github/workflows/link-check-deploy.yml
  .prettierignore
  .restyled.yaml
  README.md
  config/link-check/config.yml
  config/link-check/excluded-links.yml
  content/docs/index.md
  content/docs/self-hosted-runners.md
  gatsby-config.js
  package.json
  redirects-list.json
  yarn.lock
Labels: documentation, priority-0, website

#78 Uppercase repo_token
  content/docs/cml-with-dvc.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/start/gitlab.md
  content/docs/usage.md
  content/index.mdx
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation

#79 Remove extraneous GitLab callout
  content/docs/start/github.md
Labels: documentation

#85 Fix Azure credential documentation
  content/docs/self-hosted-runners.md
Labels: documentation

#81 Update obsolete container repository names
  content/docs/cml-with-dvc.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/start/gitlab.md
  content/docs/usage.md
  content/index.mdx
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation

#88 Refactor cml-runner access token documentation
  content/docs/self-hosted-runners.md
Labels: documentation

#89 minor formatting
  content/docs/self-hosted-runners.md
Labels: documentation

#84 fix broken links
  README.md
  config/link-check/excluded-links.yml
  content/docs/start/index.md
  src/components/organisms/SubscribeSection/Form/index.tsx
Labels: 🏠 housekeeping, website

#90 Remove GitHub-specific syntax from self-hosted runners page
  content/docs/self-hosted-runners.md
Labels: documentation

#91 Improve on-premise runners section
  content/docs/self-hosted-runners.md
Labels: documentation

#92 Convert H3 in H4 for H3 childs
  content/docs/self-hosted-runners.md
Labels: design

#98 update favicon
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon-512x512.png
  static/favicon.ico
Labels: website
