Repository iterative/cml.dev, pull requests merged in 2022-10, with the labels that each got.

#323 Update release guide for maintainers
  content/docs/contributing/core.md
Labels: documentation, housekeeping

#339 Add Bitbucket to supported platforms
  src/components/pages/Home/HeroSection/index.tsx
Labels: housekeeping, A: website

#321 Fix secret name
  content/docs/self-hosted-runners.md
Labels: documentation, external-request

#341 REPO_TOKEN clarification
  content/docs/self-hosted-runners.md
Labels: documentation

#344 ref/comment: update --publish options
  content/docs/ref/comment.md
Labels: documentation, C: ref

#352 fix tabs
  content/docs/usage.md
Labels: documentation, p0-critical, A: website, bug

#354 docs: clarify sections
  content/docs/cml-with-dvc.md
  content/docs/index.md
  content/docs/self-hosted-runners.md
  content/docs/start/bitbucket.md
  content/docs/start/github.md
  content/docs/start/gitlab.md
  content/docs/usage.md
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation, A: website, C: start

#356 docs: fixup GitLab workflows
  content/docs/self-hosted-runners.md
  content/docs/start/gitlab.md
  content/docs/usage.md
  src/components/organisms/Tooltip/types.json
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation, p1-important, design, A: website, bug, C: start, website: eng-doc

#358 docs: fixup Bitbucket workflows
  content/docs/start/bitbucket.md
  content/docs/usage.md
Labels: documentation, A: website, C: start

#357 docs: fixup GitHub workflows
  content/docs/cml-with-dvc.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/usage.md
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation, p1-important, design, A: website, bug, C: start, website: eng-doc

#360 doc/cml-with-dvc: add GitLab
  content/docs/cml-with-dvc.md
  content/docs/usage.md
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation, enhancement, p1-important
