Repository iterative/cml.dev, pull requests merged in 2022-07, with the labels that each got.

#262 docs: Update GHA workflow timeout to 35 days
  content/docs/ref/runner.md
  content/docs/self-hosted-runners.md
Labels: documentation, external-request

#264 Document additional `cml pr` options
  content/docs/ref/pr.md
Labels: documentation, external-request

#274 helper for docs writing
  package.json
Labels: enhancement, housekeeping

#275 update & sync getting started guides
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/start/gitlab.md
Labels: documentation
