Repository iterative/cml.dev, pull requests merged in 2022-06, with the labels that each got.

#253 ref/send-comment: PAT required for GitHub --update
  content/docs/ref/send-comment.md
Labels: documentation

#252 GitHub: checkout with head ref
  content/docs/cml-with-dvc.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/usage.md
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation, p1-important

#254 Document `cml send-github-check` authentication
  content/docs/ref/send-github-check.md
Labels: documentation

#256 docs: admonitions, fenced blocks, missing ref options
  content/docs/contributing/core.md
  content/docs/install.md
  content/docs/ref/pr.md
  content/docs/ref/publish.md
  content/docs/ref/runner.md
  content/docs/ref/send-comment.md
  content/docs/ref/send-github-check.md
  content/docs/ref/tensorboard-dev.md
  content/docs/self-hosted-runners.md
  content/docs/start/github.md
  content/docs/start/gitlab.md
  content/docs/usage.md
Labels: documentation

#242 Runner improvements
  content/docs/cml-with-dvc.md
  content/docs/ref/runner.md
  content/docs/self-hosted-runners.md
Labels: documentation

#257 Create Bitbucket getting started guide
  content/docs/sidebar.json
  content/docs/start/bitbucket.md
  static/img/bitbucket_cml_first_report.png
  static/img/bitbucket_fork_cml_project.png
  static/img/bitbucket_make_pr.png
Labels: documentation

#261 Fix Pull Request Commit Links installation link
  content/docs/ref/send-comment.md
Labels: documentation, bug
