Repository iterative/cml.dev, pull requests merged in 2022-12, with the labels that each got.

#407 guide/dvc: fix gitlab
  content/docs/cml-with-dvc.md
Labels: documentation, bug, C: guide

#408 home: fixup bitbucket
  src/components/pages/Home/UseCasesSection/index.tsx
Labels: documentation

#422 Using reusable workflow for check deployment
  .github/workflows/check-deployment.yml
Labels: pass-ci

#423 self-hosted-runners: add admonitions, clarifications
  content/docs/self-hosted-runners.md
Labels: documentation, C: guide

#417 Improve docs on how to use local runners
  content/docs/self-hosted-runners.md
Labels: documentation, enhancement

#415 Document comment target flag and provide examples.
  content/docs/ref/comment.md
  content/docs/ref/pr.md
  content/docs/start/github.md
Labels: documentation, enhancement, blocked, C: ref, C: start
